### ISSUE TITLE
Change schema for User entity to: SK = USER, PK = USER#<Username>

### ISSUE THREAD

**Issue by zdev24** [alexdebrie/dynamodb-instagram#47]
I see there is just CRUD access pattern for "user" entity from the requirement. However, it should not impact the remaining but getting more feature "List user, view and sort user by username" if we have some small change on the schema as following:
Currently, the entity chart for User is: PK = "USER#< Username >", SK = "USER#< Username >"

Change to: PK = USER, SK = "USER#< Username >".

How do you think? Am I wrong somewhere in understanding the sample code? @alexdebrie

**Comment by alexdebrie** [comment]
Hey @zdev24, thanks for reaching out.

The downside with the proposed update is that all user records would be in the same item collection which could lead to hot partition issues. It does enable the 'List by username' functionality, but that's not a super common one in my experience -- if you have thousands or even hundreds of users, alphabetically searching of the name won't be super helpful. Given that, I'd prefer the PK distribution benefits you'd get by not sharing the same partition key.

What do you think? Will keep the issue open for now :)

**Comment by zdev24** [comment]
Yes, I see your point for this basic sample. I just want to make sure I understand it correctly. Thanks for your response!

**Comment by alexdebrie** [comment]
Sure thing! Closing :)
